server {
    listen 9000;
    server_name localhost;
    server_tokens off;

    client_max_body_size 20M;
    
    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/api/;
    }
    
    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/admin/;
    }
    
    location /static/admin/ {
        alias /app/static/admin/;
    }

    location /static/rest_framework/ {
        alias /app/static/rest_framework/;
    }
    
    location /static/ {
        alias /app/static/static/;
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        alias /app/static/;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}